/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSppIndexRouteImport } from './routes/_authenticated/spp/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedCashflowIndexRouteImport } from './routes/_authenticated/cashflow/index'
import { Route as AuthenticatedAcademicYearsIndexRouteImport } from './routes/_authenticated/academic-years/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedTeachersPerformaRouteImport } from './routes/_authenticated/teachers/performa'
import { Route as AuthenticatedTeachersAssignmentsRouteImport } from './routes/_authenticated/teachers/assignments'
import { Route as AuthenticatedTeachersIdRouteImport } from './routes/_authenticated/teachers/$id'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'
import { Route as AuthenticatedSppPaymentTypesRouteImport } from './routes/_authenticated/spp/payment-types'
import { Route as AuthenticatedSppLaporanRouteImport } from './routes/_authenticated/spp/laporan'
import { Route as AuthenticatedSppDiscountsRouteImport } from './routes/_authenticated/spp/discounts'
import { Route as AuthenticatedSppAddPaymentRouteImport } from './routes/_authenticated/spp/add-payment'
import { Route as AuthenticatedSppStudentIdRouteImport } from './routes/_authenticated/spp/$studentId'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCashflowLaporanRouteImport } from './routes/_authenticated/cashflow/laporan'
import { Route as AuthenticatedCashflowCategoriesRouteImport } from './routes/_authenticated/cashflow/categories'
import { Route as AuthenticatedCashflowCashFlowRouteImport } from './routes/_authenticated/cashflow/cash-flow'
import { Route as AuthenticatedCashflowAkunRouteImport } from './routes/_authenticated/cashflow/akun'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppIndexRoute = AuthenticatedSppIndexRouteImport.update({
  id: '/spp/',
  path: '/spp/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashflowIndexRoute =
  AuthenticatedCashflowIndexRouteImport.update({
    id: '/cashflow/',
    path: '/cashflow/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicYearsIndexRoute =
  AuthenticatedAcademicYearsIndexRouteImport.update({
    id: '/academic-years/',
    path: '/academic-years/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedTeachersPerformaRoute =
  AuthenticatedTeachersPerformaRouteImport.update({
    id: '/teachers/performa',
    path: '/teachers/performa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersAssignmentsRoute =
  AuthenticatedTeachersAssignmentsRouteImport.update({
    id: '/teachers/assignments',
    path: '/teachers/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersIdRoute = AuthenticatedTeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSppPaymentTypesRoute =
  AuthenticatedSppPaymentTypesRouteImport.update({
    id: '/spp/payment-types',
    path: '/spp/payment-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppLaporanRoute = AuthenticatedSppLaporanRouteImport.update({
  id: '/spp/laporan',
  path: '/spp/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSppDiscountsRoute =
  AuthenticatedSppDiscountsRouteImport.update({
    id: '/spp/discounts',
    path: '/spp/discounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppAddPaymentRoute =
  AuthenticatedSppAddPaymentRouteImport.update({
    id: '/spp/add-payment',
    path: '/spp/add-payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppStudentIdRoute =
  AuthenticatedSppStudentIdRouteImport.update({
    id: '/spp/$studentId',
    path: '/spp/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashflowLaporanRoute =
  AuthenticatedCashflowLaporanRouteImport.update({
    id: '/cashflow/laporan',
    path: '/cashflow/laporan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashflowCategoriesRoute =
  AuthenticatedCashflowCategoriesRouteImport.update({
    id: '/cashflow/categories',
    path: '/cashflow/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashflowCashFlowRoute =
  AuthenticatedCashflowCashFlowRouteImport.update({
    id: '/cashflow/cash-flow',
    path: '/cashflow/cash-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashflowAkunRoute =
  AuthenticatedCashflowAkunRouteImport.update({
    id: '/cashflow/akun',
    path: '/cashflow/akun',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/cashflow/akun': typeof AuthenticatedCashflowAkunRoute
  '/cashflow/cash-flow': typeof AuthenticatedCashflowCashFlowRoute
  '/cashflow/categories': typeof AuthenticatedCashflowCategoriesRoute
  '/cashflow/laporan': typeof AuthenticatedCashflowLaporanRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/spp/add-payment': typeof AuthenticatedSppAddPaymentRoute
  '/spp/discounts': typeof AuthenticatedSppDiscountsRoute
  '/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/spp/payment-types': typeof AuthenticatedSppPaymentTypesRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/assignments': typeof AuthenticatedTeachersAssignmentsRoute
  '/teachers/performa': typeof AuthenticatedTeachersPerformaRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/cashflow/': typeof AuthenticatedCashflowIndexRoute
  '/classes/': typeof AuthenticatedClassesIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/spp/': typeof AuthenticatedSppIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cashflow/akun': typeof AuthenticatedCashflowAkunRoute
  '/cashflow/cash-flow': typeof AuthenticatedCashflowCashFlowRoute
  '/cashflow/categories': typeof AuthenticatedCashflowCategoriesRoute
  '/cashflow/laporan': typeof AuthenticatedCashflowLaporanRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/spp/add-payment': typeof AuthenticatedSppAddPaymentRoute
  '/spp/discounts': typeof AuthenticatedSppDiscountsRoute
  '/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/spp/payment-types': typeof AuthenticatedSppPaymentTypesRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/assignments': typeof AuthenticatedTeachersAssignmentsRoute
  '/teachers/performa': typeof AuthenticatedTeachersPerformaRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/academic-years': typeof AuthenticatedAcademicYearsIndexRoute
  '/cashflow': typeof AuthenticatedCashflowIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/spp': typeof AuthenticatedSppIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cashflow/akun': typeof AuthenticatedCashflowAkunRoute
  '/_authenticated/cashflow/cash-flow': typeof AuthenticatedCashflowCashFlowRoute
  '/_authenticated/cashflow/categories': typeof AuthenticatedCashflowCategoriesRoute
  '/_authenticated/cashflow/laporan': typeof AuthenticatedCashflowLaporanRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/_authenticated/spp/add-payment': typeof AuthenticatedSppAddPaymentRoute
  '/_authenticated/spp/discounts': typeof AuthenticatedSppDiscountsRoute
  '/_authenticated/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/_authenticated/spp/payment-types': typeof AuthenticatedSppPaymentTypesRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/_authenticated/teachers/assignments': typeof AuthenticatedTeachersAssignmentsRoute
  '/_authenticated/teachers/performa': typeof AuthenticatedTeachersPerformaRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/academic-years/': typeof AuthenticatedAcademicYearsIndexRoute
  '/_authenticated/cashflow/': typeof AuthenticatedCashflowIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/spp/': typeof AuthenticatedSppIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/cashflow/akun'
    | '/cashflow/cash-flow'
    | '/cashflow/categories'
    | '/cashflow/laporan'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/spp/$studentId'
    | '/spp/add-payment'
    | '/spp/discounts'
    | '/spp/laporan'
    | '/spp/payment-types'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/assignments'
    | '/teachers/performa'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/academic-years/'
    | '/cashflow/'
    | '/classes/'
    | '/events/'
    | '/settings/'
    | '/spp/'
    | '/students/'
    | '/teachers/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cashflow/akun'
    | '/cashflow/cash-flow'
    | '/cashflow/categories'
    | '/cashflow/laporan'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/spp/$studentId'
    | '/spp/add-payment'
    | '/spp/discounts'
    | '/spp/laporan'
    | '/spp/payment-types'
    | '/students/$id'
    | '/teachers/$id'
    | '/teachers/assignments'
    | '/teachers/performa'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/academic-years'
    | '/cashflow'
    | '/classes'
    | '/events'
    | '/settings'
    | '/spp'
    | '/students'
    | '/teachers'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/cashflow/akun'
    | '/_authenticated/cashflow/cash-flow'
    | '/_authenticated/cashflow/categories'
    | '/_authenticated/cashflow/laporan'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/spp/$studentId'
    | '/_authenticated/spp/add-payment'
    | '/_authenticated/spp/discounts'
    | '/_authenticated/spp/laporan'
    | '/_authenticated/spp/payment-types'
    | '/_authenticated/students/$id'
    | '/_authenticated/teachers/$id'
    | '/_authenticated/teachers/assignments'
    | '/_authenticated/teachers/performa'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/academic-years/'
    | '/_authenticated/cashflow/'
    | '/_authenticated/classes/'
    | '/_authenticated/events/'
    | '/_authenticated/settings/'
    | '/_authenticated/spp/'
    | '/_authenticated/students/'
    | '/_authenticated/teachers/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/': {
      id: '/_authenticated/spp/'
      path: '/spp'
      fullPath: '/spp/'
      preLoaderRoute: typeof AuthenticatedSppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow/': {
      id: '/_authenticated/cashflow/'
      path: '/cashflow'
      fullPath: '/cashflow/'
      preLoaderRoute: typeof AuthenticatedCashflowIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/': {
      id: '/_authenticated/academic-years/'
      path: '/academic-years'
      fullPath: '/academic-years/'
      preLoaderRoute: typeof AuthenticatedAcademicYearsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/teachers/performa': {
      id: '/_authenticated/teachers/performa'
      path: '/teachers/performa'
      fullPath: '/teachers/performa'
      preLoaderRoute: typeof AuthenticatedTeachersPerformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/assignments': {
      id: '/_authenticated/teachers/assignments'
      path: '/teachers/assignments'
      fullPath: '/teachers/assignments'
      preLoaderRoute: typeof AuthenticatedTeachersAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/$id': {
      id: '/_authenticated/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof AuthenticatedTeachersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/payment-types': {
      id: '/_authenticated/spp/payment-types'
      path: '/spp/payment-types'
      fullPath: '/spp/payment-types'
      preLoaderRoute: typeof AuthenticatedSppPaymentTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/laporan': {
      id: '/_authenticated/spp/laporan'
      path: '/spp/laporan'
      fullPath: '/spp/laporan'
      preLoaderRoute: typeof AuthenticatedSppLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/discounts': {
      id: '/_authenticated/spp/discounts'
      path: '/spp/discounts'
      fullPath: '/spp/discounts'
      preLoaderRoute: typeof AuthenticatedSppDiscountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/add-payment': {
      id: '/_authenticated/spp/add-payment'
      path: '/spp/add-payment'
      fullPath: '/spp/add-payment'
      preLoaderRoute: typeof AuthenticatedSppAddPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/$studentId': {
      id: '/_authenticated/spp/$studentId'
      path: '/spp/$studentId'
      fullPath: '/spp/$studentId'
      preLoaderRoute: typeof AuthenticatedSppStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow/laporan': {
      id: '/_authenticated/cashflow/laporan'
      path: '/cashflow/laporan'
      fullPath: '/cashflow/laporan'
      preLoaderRoute: typeof AuthenticatedCashflowLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow/categories': {
      id: '/_authenticated/cashflow/categories'
      path: '/cashflow/categories'
      fullPath: '/cashflow/categories'
      preLoaderRoute: typeof AuthenticatedCashflowCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow/cash-flow': {
      id: '/_authenticated/cashflow/cash-flow'
      path: '/cashflow/cash-flow'
      fullPath: '/cashflow/cash-flow'
      preLoaderRoute: typeof AuthenticatedCashflowCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow/akun': {
      id: '/_authenticated/cashflow/akun'
      path: '/cashflow/akun'
      fullPath: '/cashflow/akun'
      preLoaderRoute: typeof AuthenticatedCashflowAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCashflowAkunRoute: typeof AuthenticatedCashflowAkunRoute
  AuthenticatedCashflowCashFlowRoute: typeof AuthenticatedCashflowCashFlowRoute
  AuthenticatedCashflowCategoriesRoute: typeof AuthenticatedCashflowCategoriesRoute
  AuthenticatedCashflowLaporanRoute: typeof AuthenticatedCashflowLaporanRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSppStudentIdRoute: typeof AuthenticatedSppStudentIdRoute
  AuthenticatedSppAddPaymentRoute: typeof AuthenticatedSppAddPaymentRoute
  AuthenticatedSppDiscountsRoute: typeof AuthenticatedSppDiscountsRoute
  AuthenticatedSppLaporanRoute: typeof AuthenticatedSppLaporanRoute
  AuthenticatedSppPaymentTypesRoute: typeof AuthenticatedSppPaymentTypesRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedTeachersIdRoute: typeof AuthenticatedTeachersIdRoute
  AuthenticatedTeachersAssignmentsRoute: typeof AuthenticatedTeachersAssignmentsRoute
  AuthenticatedTeachersPerformaRoute: typeof AuthenticatedTeachersPerformaRoute
  AuthenticatedAcademicYearsIndexRoute: typeof AuthenticatedAcademicYearsIndexRoute
  AuthenticatedCashflowIndexRoute: typeof AuthenticatedCashflowIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedSppIndexRoute: typeof AuthenticatedSppIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCashflowAkunRoute: AuthenticatedCashflowAkunRoute,
  AuthenticatedCashflowCashFlowRoute: AuthenticatedCashflowCashFlowRoute,
  AuthenticatedCashflowCategoriesRoute: AuthenticatedCashflowCategoriesRoute,
  AuthenticatedCashflowLaporanRoute: AuthenticatedCashflowLaporanRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSppStudentIdRoute: AuthenticatedSppStudentIdRoute,
  AuthenticatedSppAddPaymentRoute: AuthenticatedSppAddPaymentRoute,
  AuthenticatedSppDiscountsRoute: AuthenticatedSppDiscountsRoute,
  AuthenticatedSppLaporanRoute: AuthenticatedSppLaporanRoute,
  AuthenticatedSppPaymentTypesRoute: AuthenticatedSppPaymentTypesRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedTeachersIdRoute: AuthenticatedTeachersIdRoute,
  AuthenticatedTeachersAssignmentsRoute: AuthenticatedTeachersAssignmentsRoute,
  AuthenticatedTeachersPerformaRoute: AuthenticatedTeachersPerformaRoute,
  AuthenticatedAcademicYearsIndexRoute: AuthenticatedAcademicYearsIndexRoute,
  AuthenticatedCashflowIndexRoute: AuthenticatedCashflowIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedSppIndexRoute: AuthenticatedSppIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
